### ISSUE TITLE
有些全形標點符號不是全形寬度

### ISSUE THREAD

**Issue by zaqxs123456** [ButTaiwan/gensen-font#10]
有些全形標點符號不是全形寬度：
「」【】〔〕《》

但圓括號跟其他一些就是全形寬度：
（）；、，。

**Comment by ButTaiwan** [comment]
Ver 1.500 更新 (2020/4/11)
假名與引號類橫排時改為比例寬

這是1.500版的規格。
若有需要使用全形，可啟用 fwid, salt 或 ss01 特性。

![image](https://user-images.githubusercontent.com/5418570/82056623-cafd3580-96f4-11ea-97a2-a4dfb3bec0eb.png)
