### ISSUE TITLE
標點寬度不一，同時應為全形(full width)

### ISSUE THREAD

**Issue by nodegin** [ButTaiwan/gensen-font#13]
<img width="302" alt="Screenshot 2020-06-17 at 5 38 48 AM" src="https://user-images.githubusercontent.com/8536244/84830848-d679ae80-b05c-11ea-900e-2f3f6ed430d2.png">

**Comment by ButTaiwan** [comment]
![image](https://user-images.githubusercontent.com/5418570/85087702-ca365280-b210-11ea-826c-5040f7740628.png)
