### ISSUE TITLE
TW 版本的字體"輸"字錯誤

### ISSUE THREAD

**Issue by Mg138** [ButTaiwan/gensen-font#15]
TW版本

![image](https://user-images.githubusercontent.com/33348966/91465770-cc77f580-e8c0-11ea-9fee-be540e48ba8e.png)

JP版本

![image](https://user-images.githubusercontent.com/33348966/91465794-d6015d80-e8c0-11ea-88ab-6f99a821f392.png)

**Comment by Mg138** [comment]
查了一下 這是KR的寫法

**Comment by ButTaiwan** [comment]
專案頁有說明TW版本一律採用傳統印刷體風格。
也就是台灣鉛字印刷物上最常見的寫法。

這是國語日報字典：
![IMG_20200828_010210](https://user-images.githubusercontent.com/5418570/91472761-81fb7680-e8ca-11ea-81c1-9a8bbe1bf8f3.jpg)
