### ISSUE TITLE
請問關於姬這個字

### ISSUE THREAD

**Issue by hahadown** [ButTaiwan/gensen-font#16]
右半邊能不能修改漂亮些呢?
姬右半邊內的口變得很奇怪，變成有一條線，不好看XD
回報一下，謝謝

**Comment by ButTaiwan** [comment]
原則上本專案大原則是對於思源本來就收的字，只從思源本家原有的字符選擇一個，絕不人工調整。

至於應該選擇何者為佳，因為目標是收錄傳統印刷體，而

說文解字長這樣
![image](https://user-images.githubusercontent.com/5418570/93726859-d7395800-fbea-11ea-95ec-e8bbc45f8244.png)

康熙字典長這樣
![image](https://user-images.githubusercontent.com/5418570/93726865-e1f3ed00-fbea-11ea-9088-35c3b48de57a.png)

故目前選擇的字符應是正確的。

**Comment by hahadown** [comment]
原來如此，又上了一課
原來看習慣的也不見得是正確的
謝謝您!!
