### ISSUE TITLE
誤拔腳記錄

### ISSUE THREAD

**Issue by cathree3** [ButTaiwan/gensen-font#2]
關墮氰悲棐辈輩湧
![default](https://user-images.githubusercontent.com/13507992/51370843-613a3f00-1b33-11e9-8e51-fe1414b649d8.png)

**Comment by zaurione** [comment]
猆字问题同上

**Comment by weimming** [comment]
「靡」字下面的「非」右下角誤拔腳，在此回報。

**Comment by ButTaiwan** [comment]
![image](https://user-images.githubusercontent.com/5418570/79038851-4c9e0700-7c0f-11ea-9d02-1f0973da0db1.png)
