### ISSUE TITLE
JP版本中的「复」字好像宽度过窄？

### ISSUE THREAD

**Issue by ethericdeer** [ButTaiwan/gensen-font#21]
<img width="173" alt="image" src="https://user-images.githubusercontent.com/17719927/168104326-28fb0e7a-d744-4a72-a7e3-32f5e947c5ae.png">
两个版本的对比

**Comment by Ostrichbeta** [comment]
一般的日本字型「复」字都是這樣寫的，沒有問題

**Comment by ButTaiwan** [comment]
JP版本依照思源JP版本原始字樣不做調整。
