### ISSUE TITLE
「部」字的兩點形狀問題

### ISSUE THREAD

**Issue by Ostrichbeta** [ButTaiwan/gensen-font#3]
![image](https://user-images.githubusercontent.com/25266479/46580253-ca78c500-ca10-11e8-8e63-9d6d1240565b.png)
如圖，部字的兩點下端沒有園化，在Bold等級下看得比較清楚

**Comment by cathree3** [comment]
如果 Adobe 提供未閉合曲線的字體，修改效果會更優嗎？

**Comment by ButTaiwan** [comment]
> 如圖，部字的兩點下端沒有園化，在Bold等級下看得比較清楚

有部分沾黏的筆劃，程式無法正確判過這是單獨筆劃。以自動改作來說，這是很難解的。
愈粗的字重這種問題會更多。 Bold, Heavy 腳拔不掉的情況與這種筆劃無法圓化的情形都非常多。
除非能想到更好的演算法...

> 如果 Adobe 提供未閉合曲線的字體，修改效果會更優嗎？

會，至少誤判情形會少非常多。但是目前沒有會提供的跡象。
（但怎麼拔腳可能變另一個難題）
