### ISSUE TITLE
希望这个项目也能有大陆字形版本

### ISSUE THREAD

**Issue by ShuueenN** [ButTaiwan/gensen-font#5]
很喜欢这套改编字体，做出了就连日本友人都没有做出的样式。大陆的文本字体一直不多，这样万金油的圆体更是少之又少，简化过的汉字也应该不会费太大力气修bug，希望这位大大也可以做一套大陆版本出来！

**Comment by ButTaiwan** [comment]
目前沒有做GB版本的計畫。
