### ISSUE TITLE
字型档名太长

### ISSUE THREAD

**Issue by NightFurySL2001** [ButTaiwan/gensen-font#8]
安装后在 Windows 简体中文 Office 系列下显示过长，出现2个名字：
GenSenMaruGothic TW TTF ExtraLi （可正常使用） 与 GenSenMaruGothic TW TTF ExtraL （无法正常使用）

![image](https://user-images.githubusercontent.com/33471049/72137352-a18a7100-33c5-11ea-9653-9bb6c5f16cf2.png)
![image](https://user-images.githubusercontent.com/33471049/72137367-aa7b4280-33c5-11ea-972c-a878b4a8aac7.png)

名字已超过31个字符 TrueType 限制。

**Comment by ButTaiwan** [comment]
Ver 1.500 起已改名 GenSenRounded ，且字重全部改成縮寫 EL, L, R, M, B, H。
